export const data = {
  Actors: 'Rico Verhoeven, Frank Grillo, Marie Dompnier',
  Awards: 'N/A',
  BoxOffice: 'N/A',
  Country: 'United States, Netherlands',
  DVD: 'N/A',
  Director: 'Todor Chapkanov',
  Genre: 'Action, Thriller',
  Language: 'English',
  Metascore: 'N/A',
  Plot: "An ex-special forces operative wages a one man war through the streets of Amsterdam to rescue his friend's daughter from the local crime syndicate.",
  Poster:
    'https://m.media-amazon.com/images/M/MV5BODkxZmNmOWYtNTI0Ny00NDA3LWJlMWItZDI4MWYzYWMzYmU5XkEyXkFqcGdeQXVyMTU1NTc0MzY@._V1_SX300.jpg',
  Production: 'N/A',
  Rated: 'N/A',
  Released: '13 Apr 2023',
  Response: 'True',
  Runtime: '90 min',
  Title: 'Black Lotus',
  Type: 'movie',
  Website: 'N/A',
  Writer: 'Tad Daggerhart',
  Year: '2023',
  imdbID: 'tt15895490',
  imdbRating: '4.2',
  imdbVotes: '1,371',
};
